### ISSUE TITLE
showDirections not working on disabled map app

### ISSUE THREAD

**Issue by yairsts** [mattermoran/map_launcher#137]
When I try open disabled app in android, I got this error:

 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://www.google.com/... flg=0x10000000 pkg=com.google.android.apps.maps }, null, android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://www.google.com/... flg=0x10000000 pkg=com.google.android.apps.maps }
 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2051)
 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1709)
 	at android.app.ContextImpl.startActivity(ContextImpl.java:957)
 	at android.app.ContextImpl.startActivity(ContextImpl.java:928)
 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
 	at com.alexmiller.map_launcher.MapLauncherPlugin.launchMap(MapLauncherPlugin.kt:90)
 	at com.alexmiller.map_launcher.MapLauncherPlugin.onMethodCall(MapLauncherPlugin.kt:113)
 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
 	at android.os.Handler.handleCallback(Handler.java:883)
 	at android.os.Handler.dispatchMessage(Handler.java:100)
 	at android.os.Looper.loop(Looper.java:214)
 	at android.app.ActivityThread.main(ActivityThread.java:7356)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

try & catch does not work, because the error in the native android code.

**Comment by mattermoran** [comment]
It should be fixed once https://github.com/mattermoran/map_launcher/pull/136 gets merged
