### ISSUE TITLE
No Activity found to handle Intent [Google Maps on Android 10 SDK 29)

### ISSUE THREAD

**Issue by k-zen** [mattermoran/map_launcher#71]
I getting this error when trying to open Google Maps (`showMarker()`) on an Android 10 compiled with SDK 30. I can assert that Google Maps is installed and that it is present in the list of available maps.

```
E/MethodChannel#map_launcher(14912): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=geo:0,0?q=-25.2,-57.5(some_text)&zoom=16 flg=0x10000000 pkg=com.google.android.apps.maps }
E/MethodChannel#map_launcher(14912): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
E/MethodChannel#map_launcher(14912): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
E/MethodChannel#map_launcher(14912): 	at android.app.ContextImpl.startActivity(ContextImpl.java:958)
E/MethodChannel#map_launcher(14912): 	at android.app.ContextImpl.startActivity(ContextImpl.java:929)
E/MethodChannel#map_launcher(14912): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
E/MethodChannel#map_launcher(14912): 	at com.alexmiller.map_launcher.MapLauncherPlugin.launchMap(MapLauncherPlugin.kt:86)
E/MethodChannel#map_launcher(14912): 	at com.alexmiller.map_launcher.MapLauncherPlugin.onMethodCall(MapLauncherPlugin.kt:109)
E/MethodChannel#map_launcher(14912): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#map_launcher(14912): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#map_launcher(14912): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#map_launcher(14912): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#map_launcher(14912): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#map_launcher(14912): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#map_launcher(14912): 	at android.app.ActivityThread.main(ActivityThread.java:7386)
E/MethodChannel#map_launcher(14912): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#map_launcher(14912): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#map_launcher(14912): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```

```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.1 20C69 darwin-x64, locale en-CA)
    • Flutter version 2.0.4 at /Users/akc/Applications/flutter
    • Framework revision b1395592de (7 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/akc/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/akc/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 55.0.4
    • Dart plugin version 203.7759

[✓] Connected device (2 available)
    • Nokia 3 1 Plus (mobile) • ROOGAJG930901259 • android-arm64  • Android 10 (API 29)
    • Chrome (web)            • chrome           • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

**Comment by mattermoran** [comment]
If you try to run example project google maps also doesn't show up in the list of available maps?

**Comment by k-zen** [comment]
This is the list of available maps on the device I'm using:
`[AvailableMap { mapName: Google Maps, mapType: google }]`

**Comment by k-zen** [comment]
It open correctly on iOS.

**Comment by mattermoran** [comment]
> This is the list of available maps on the device I'm using:
> `[AvailableMap { mapName: Google Maps, mapType: google }]`

so it says google maps is available on android but it fails to launch it using example project as well?

**Comment by k-zen** [comment]
> so it says google maps is available on android but it fails to launch it using example project as well?

This is correct. I managed to solve the issue... Google Maps was installed but **disabled**, and that cause the error to happen. Once I enabled it, I was able to launch it successfully.

I suppose with a simple `try-catch` I can test for enable/disable state on a given map at the OS level.

```
if (await MapLauncher.isMapAvailable(MapType.google)) {
  try {
    await MapLauncher.showMarker(
      mapType: MapType.google,
      coords: Coords(lat, lon),
      title: '...',
    );
  } on Exception catch (_) {
    // If we reach here, then the map must be disabled...
  }
}
```

**Comment by mattermoran** [comment]
Interesting. I don't think there's a way to check if the map is disabled though so try/catch is probably the only option :(

**Comment by broiniac** [comment]
Stumbled upon same issue today, so I've made more robust version of proposed solution:

```dart

// prefixed, becouse in colission with flutter_map package
import 'package:map_launcher/map_launcher.dart' as ml; 
import 'package:flutter_map/flutter_map.dart';

...

const double latitude = 40.00;
const double longitude = 20.00;

final availableMaps = await ml.MapLauncher.installedMaps;
final int providersCount = availableMaps.length;
// Try every available map there is…
for (var i = 0; i < providersCount; i++) {
  try {
    final ml.AvailableMap mapProvider = availableMaps[i];

    await mapProvider.showDirections(
      destination: ml.Coords(latitude, longitude),
      destinationTitle: 'This is the place.',
      //origin: Coords of CurrentLocation - GDPR?
    );

    // Until You will find one, that works. Then finish.
    return;
  } on Exception catch (_) {}
}

// No working provider available? Open link in browser.
if (!await launchUrl(
  // Link to Google Maps (with pin on location).
  Uri.parse('https://www.google.com/maps?q=$latitude,$longitude'),
  mode: LaunchMode.externalApplication
)) {
  // Even this failed…
  throw 'Could not launch $url';
}

```
